const API=window.SKYGUARD_API||'http://localhost:8000';
let demo=null, filtered=[], page=0, pageSize=15;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
async function loadDemo(){
  if(!demo){const r=await fetch('data/demo-data.json'); demo=await r.json();}
  filtered=demo.rows; page=0; renderAll(); $('#message').textContent='Loaded the repository test stream: 1,000 readings and 100 diagnosed events.';
}
function renderAll(){
  const rows=demo.rows, anomalies=rows.filter(r=>r.predictedAnomaly===1).length, normal=rows.length-anomalies;
  $('#total').textContent=rows.length.toLocaleString(); $('#anomalies').textContent=anomalies.toLocaleString(); $('#normal').textContent=normal.toLocaleString(); $('#anomalyPct').textContent=(anomalies/rows.length*100).toFixed(1)+'% of stream'; $('#events').textContent=demo.events.length; $('#navAnomalyCount').textContent=anomalies;
  $('#healthRing').textContent=(normal/rows.length*100).toFixed(1)+'%';
  $('#f1').textContent=demo.metrics.f1_score.toFixed(3); $('#algorithm').textContent=demo.model.algorithm; $('#threshold').textContent=demo.model.decision_threshold.toFixed(4);
  renderFaults(rows); renderLatest(rows.slice(-8).reverse()); renderEvents(); renderReadings(); drawChart(rows);
}
function renderFaults(rows){const counts={}; rows.forEach(r=>{let f=r.fault==='NO_FAULT'?'Normal':r.fault;counts[f]=(counts[f]||0)+1}); const list=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5), max=list[0]?.[1]||1; $('#faultBars').innerHTML=list.map(([name,n])=>`<div class="fault-line"><div class="fault-meta"><span>${name.replaceAll('_',' ')}</span><b>${n}</b></div><div class="fault-track"><div class="fault-fill" style="width:${n/max*100}%"></div></div></div>`).join('')}
function status(r){return r.predictedAnomaly?'<span class="status-tag anomaly">ANOMALY</span>':'<span class="status-tag normal">NORMAL</span>'}
function renderLatest(rows){$('#latestBody').innerHTML=rows.map(r=>`<tr><td>${new Date(r.datetime).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}</td><td>${r.temperature.toFixed(1)}°C</td><td>${r.pressure.toFixed(1)}</td><td>${r.humidity.toFixed(1)}%</td><td>${status(r)}</td></tr>`).join('')}
function renderEvents(){const sev=$('#severityFilter').value;let events=demo.events.filter(e=>sev==='all'||e.severity===sev);$('#eventsBody').innerHTML=events.slice(0,100).map(e=>`<tr><td>${new Date(e.start).toLocaleString()}</td><td>${String(e.fault).replaceAll('_',' ')}</td><td>${String(e.affected_sensors||'—').replaceAll('_',' ')}</td><td><span class="severity sev-${String(e.severity).toLowerCase()}">${e.severity}</span></td><td>${(Number(e.anomaly_confidence)*100).toFixed(0)}%</td><td>${e.qc_action||'—'}</td></tr>`).join('')}
function renderReadings(){const q=($('#search')?.value||'').toLowerCase(); filtered=demo.rows.filter(r=>`${r.datetime} ${r.fault} ${r.anomalyType} ${r.predictedAnomaly?'anomaly':'normal'}`.toLowerCase().includes(q));const start=page*pageSize, slice=filtered.slice(start,start+pageSize);$('#readingsBody').innerHTML=slice.map((r,i)=>`<tr><td>${start+i+1}</td><td>${r.datetime}</td><td>${r.temperature.toFixed(1)} °C</td><td>${r.pressure.toFixed(1)} hPa</td><td>${r.humidity.toFixed(1)} %</td><td>${r.score.toFixed(2)}</td><td>${status(r)}</td></tr>`).join('');$('#tableInfo').textContent=`${filtered.length?start+1:0}–${Math.min(start+pageSize,filtered.length)} of ${filtered.length.toLocaleString()}`;$('#prev').disabled=page===0;$('#next').disabled=start+pageSize>=filtered.length}
function drawChart(rows){const c=$('#telemetryChart'),ctx=c.getContext('2d'),rect=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=rect.width*dpr;c.height=rect.height*dpr;ctx.scale(dpr,dpr);const w=rect.width,h=rect.height,p=24, sample=rows.filter((_,i)=>i%8===0), vals=sample.map(r=>r.temperature), min=Math.min(...vals)-1,max=Math.max(...vals)+1;ctx.strokeStyle='#252d40';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=p+i*(h-p*2)/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}function line(key,color,lo,hi){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();sample.forEach((r,i)=>{let v=r[key],y=h-p-(v-lo)/(hi-lo)*(h-p*2),x=p+i*(w-p*2)/(sample.length-1);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}line('temperature','#a487ff',min,max)}
async function analyzeFile(file){const msg=$('#message');msg.textContent='Sending CSV to the unchanged SkyGuard backend…';try{const f=new FormData();f.append('file',file);const res=await fetch(`${API}/api/analyze`,{method:'POST',body:f});const data=await res.json();if(!res.ok)throw Error(data.detail||'Analysis failed');demo={rows:data.results.map(x=>({datetime:`Row ${x.row}`,temperature:Number(x.values.temperature),pressure:Number(x.values.pressure),humidity:Number(x.values.humidity),predictedAnomaly:x.anomaly?1:0,actualAnomaly:x.anomaly?1:0,score:Number(x.score),fault:x.anomaly?'ANOMALY':'NO_FAULT',anomalyType:x.anomaly?'ANOMALY':'normal'})),events:[],metrics:{f1_score:0},model:{algorithm:data.detector,decision_threshold:0}};filtered=demo.rows;page=0;renderAll();msg.textContent=`Analysis complete using ${data.detector}. ${data.anomalies} anomalies flagged from ${data.total} valid readings.`}catch(e){msg.textContent=e.message}}
async function checkBackend(){const chip=$('#backendChip'),api=$('#apiStatus');try{const r=await fetch(`${API}/api/model-status`);const d=await r.json();chip.textContent=d.detector||'Available';api.textContent=d.detector||'Model endpoint online'}catch(e){chip.textContent='Offline';api.textContent='Start backend on :8000'}}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.go)));
function showSection(id){$$('.page').forEach(p=>p.classList.remove('active-page'));$('#'+id).classList.add('active-page');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.section===id));$('#pageTitle').textContent={dashboard:'Operations dashboard',anomalies:'Anomaly event log',stations:'Station data',model:'Model health'}[id]}
$('#loadDemo').addEventListener('click',loadDemo);$('#file').addEventListener('change',e=>e.target.files[0]&&analyzeFile(e.target.files[0]));$('#refresh').addEventListener('click',loadDemo);$('#severityFilter').addEventListener('change',renderEvents);$('#search').addEventListener('input',()=>{page=0;renderReadings()});$('#prev').addEventListener('click',()=>{page--;renderReadings()});$('#next').addEventListener('click',()=>{page++;renderReadings()});$('#checkBackend').addEventListener('click',checkBackend);window.addEventListener('resize',()=>demo&&drawChart(demo.rows));
loadDemo();checkBackend();
